name: ShellCheck

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'tests/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Clone uac-tests repo
        uses: actions/checkout@v4
        with:
          path: uac-tests

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
